### ISSUE TITLE
Failed to open file when trying to install via magento connect

### ISSUE THREAD

**Issue by renini** [sitewards/B2BProfessional#14]
CONNECT ERROR: Failed to open file /var/www/httpdocs/winkel/downloader/.cache/community/Sitewards_B2BProfessional-2.5.2/app/design/frontend/base/default/template/sitewards/b2bprofessional/catalog/product/view/type/bundle

**Comment by hpcodecraft** [comment]
I just ran into this exact same problem with another extension (M2Epro eBay extension) and the fix of @osvarychevskyi made it work! Thanks a lot! :)

**Comment by luisfdeandrade** [comment]
I was installing Mage Monkey extension and get the same problem, the fix suggest worked for this one too. Thank you!

**Comment by AndreKelling** [comment]
`Hope this will help you.`
@osvarychevskyi   it does!

**Comment by anhuy1989** [comment]
@osvarychevskyi Perfect, thanks

**Comment by kiranpatils** [comment]
@osvarychevskyi Nice solution, its working perfectly now. thanks :+1:

**Comment by MarkHTML** [comment]
@osvarychevskyi  Worked for me too! Problem upgrading 'Interface_Adminhtml_Default' from magento connect manager
