### ISSUE TITLE
upgrading to 3.0.5 from 3.0.2 causes search pagination to fail

### ISSUE THREAD

**Issue by mattyl** [sitewards/B2BProfessional#41]
After updating on magento connect from 3.0.2 to 3.0.5 quick search returns all results instead of pagination

we tested this on a production and staging site and reversing on staging site confirmed that it was the update.

we are trying to fix this so this link may be out of date
http://staging.keene.co.uk/catalogsearch/result/?q=usb

it is showing 82 results - all 82 on page despite only allowing 12 per page

in case i cant find it, anyone have an idea why?

PS normal catalog listing is fine
http://staging.keene.co.uk/av-distribution/av-switching/hdmi.html
it is just catalogsearch

**Comment by mattyl** [comment]
I have isolated the issue to
block/catalog/product/list.php

commenting out the following resolves the issue but also removes functionality!

        Mage::dispatchEvent(

            'sitewards_b2bprofessional_product_list_collection_load_after',

            array(

                'product_collection' => $oProductCollection

            )

        );

**Comment by dmanners** [comment]
Hi @mattyl,

This event is not actually used from our code and simply is a place that can be used to attach onto to make your own extensions.

If you search your code base for this event you should be able to find the problematic event handler.

Thanks

**Comment by mattyl** [comment]
isnt this where you modify the product listing? by editing the list.php to go back in history to version 3.0.4 it no longer has the event but dispalys the same problem

this is the comment in your observer, which makes it look very important!

Checks if the product can be added to the cart and if not, adds a dummy required
     * option in order to replace the add-to-cart button's url with the view-details url

**Comment by mattyl** [comment]
further analysing this something weird i cannot explain is happening for example with this code in observer.php

    public function sitewardsB2bprofessionalProductListCollectionLoadAfter(Varien_Event_Observer $oObserver)

    {

        $opProductCollection = $oObserver->getProductCollection();

        $oDummyOption       = Mage::getModel('catalog/product_option');

        foreach ($opProductCollection as $opProduct) {

         //   if ($this->oB2BHelper->isProductActive($oProduct) === false) {

                //$oProduct->setRequiredOptions(array($oDummyOption));

         //   }

        }
		

        return $opProductCollection;

    }

the problematic behaviour in search occurs

while

    public function sitewardsB2bprofessionalProductListCollectionLoadAfter(Varien_Event_Observer $oObserver)

    {

        $opProductCollection = $oObserver->getProductCollection();

        $oDummyOption       = Mage::getModel('catalog/product_option');

        //foreach ($opProductCollection as $opProduct) {

         //   if ($this->oB2BHelper->isProductActive($oProduct) === false) {

                //$oProduct->setRequiredOptions(array($oDummyOption));

         //   }

       // }
		

        return $opProductCollection;

    }

the problem is curred - it seems simply by looping through the object without any action changes it and causes the problematic behaviour...
will continue searching - but anyone can spot the mistake please let me know!

**Comment by mattyl** [comment]
Found Solution - not sure why but the change below solves the problem of losing pagination on catalogsearch - unsure if there are knock on consequences though - but from initial tests everything seems to work fine for us

        //$oProductCollection = $oObserver->getProductCollection();
        $oProductCollection = $oObserver->getLoadedProductCollection(); // smb mod

**Comment by toh82** [comment]
well, this thingy here not only breaks the pagination, it breaks the **sortby**, too.
Right now tested @mattyl bugfix and sortby started to work again, thy for reporting the fix.

**Comment by toh82** [comment]
https://github.com/sitewards/B2BProfessional/pull/45

**Comment by toh82** [comment]
Pull request is merged, problem should be solved
