### ISSUE TITLE
Update Netzarbeiter_CustomerActivation to 0.5.7

### ISSUE THREAD

**Issue by jhoelzl** [sitewards/B2BProfessional#51]
Please integrate the update in this repo - thanks!

**Comment by jhoelzl** [comment]
Version 0.5.7 was released: https://github.com/Vinai/customer-activation/releases

**Comment by andrewhowdencom** [comment]
Hey @jhoelzl! Thanks for reporting the issue. Would you consider opening a pull request with the update to composer?

Alternatively, I shall take a look at this at 9am tomorrow. @erickpatrick perhaps there is some stream of work you can integrate testing this into?

**Comment by jhoelzl** [comment]
#61
