### ISSUE TITLE
Some errors in system.log

### ISSUE THREAD

**Issue by jhoelzl** [sitewards/B2BProfessional#54]
Hello,

my Magento system.log file is full of errors like that:

> 2016-02-18T05:10:22+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /var/www/vhosts/magento_development/magento/.modman/sitewards_b2b/app/code/community/Sitewards/B2BProfessional/Model/Observer.php on line 254

Do you have any idea how to overcome this issue?

Thanks!

**Comment by dmanners** [comment]
Hi,

Thanks for the message. We currently have not seen this problem but will have a look at it and get back to you.

**Comment by jhoelzl** [comment]
@dmanners i still have this in my daily log files. Any ideas? :)

**Comment by jhoelzl** [comment]
Maybe check the before going through the array if it is an array an has data in it? http://stackoverflow.com/questions/2630013/invalid-argument-supplied-for-foreach
