### ISSUE TITLE
Superfleus resources from ye olde netzarbieter ext

### ISSUE THREAD

**Issue by andrewhowdencom** [sitewards/B2BProfessional#63]
Ref: https://github.com/sitewards/B2BProfessional/pull/62

Need to remove these, and bump the config to 4.0.1 (with removal of orphaned resources)

**Comment by jhoelzl** [comment]
see #64

**Comment by andrewhowdencom** [comment]
Fixed in 8a03d149081bf665e645a15a92a212c2a032967e. Thanks again! (There's a limit to how often I can say this. Prooobably just gonna keep saying it in the CHangelog -- that's more permanent anyway)
